env:
  global:
    secure: "LGO/4solxrq/GNOjdQbGGpW5oQFL3YZ6eV88G8WSePpUsg07OLETPcgcGB3xfCyaRFzyJM+jauLfXY4spIVls6zygDhELUfgedtyacapT+FY5/O4M/OPCC82/4T1yBU3XLO18n1aBa2/mibTLv6QvBbHyWRFPmUPSimTiWYUxnA="

script:
- ./transifex.sh

